/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CaseMap {
boolean: boolean
caseMapEditorDataContext: CaseMapEditorDataContext
caseMapEditorProcessContext: CaseMapEditorProcessContext
caseMapEditorSaveArgs: CaseMapEditorSaveArgs
caseMapModel: CaseMapModel
processMetrics: ProcessMetrics[]
processStart: ProcessStart[]
string: string
[k: string]: unknown
}
export interface CaseMapEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface CaseMapEditorProcessContext {
  projectFilter: string;
}
export interface CaseMapEditorSaveArgs {
  context: CaseMapEditorDataContext;
  model: CaseMapModel;
}
export interface CaseMapModel {
  description: string;
  id: CaseMapId;
  name: string;
  stages: StageModel[];
  uuid: string;
}
export interface CaseMapId {
  id: string;
}
export interface StageModel {
  description: string;
  icon: string;
  id: StageId;
  isTerminating: boolean;
  name: string;
  processes: StageProcessModel[];
  sideSteps: StageProcessModel[];
}
export interface StageId {
  id: string;
}
export interface StageProcessModel {
  description: string;
  id: StageProcessId;
  name: string;
  preCondition: ProcessPreCondition;
  processToExecute: ProcessReference;
}
export interface StageProcessId {
  id: string;
}
export interface ProcessPreCondition {
  label: string;
  script: IvyScriptExpression;
}
export interface IvyScriptExpression {
  script: string;
}
export interface ProcessReference {
  value: string;
}
export interface ProcessMetrics {
  avgBusinessRuntime: number;
  onRisk: number;
  onRiskDate: string;
  onTime: number;
  overdue: number;
  processId: string;
}
export interface ProcessStart {
  description: string;
  name: string;
  processName: string;
  processReference: string;
  project: Project;
  projectName: string;
  signature: string;
  startDescription: string;
  startName: string;
  userFriendlyRequestPath: string;
}
export interface Project {}
