// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CaseMap {
boolean: boolean
caseMapContext: CaseMapContext
caseMapEditorData: CaseMapEditorData
caseMapEditorProcessContext: CaseMapEditorProcessContext
caseMapEditorSaveArgs: CaseMapEditorSaveArgs
editorFileContent: EditorFileContent
processStart: ProcessStart[]
[k: string]: unknown
}
export interface CaseMapContext {
  app: string;
  file: string;
  pmv: string;
}
export interface CaseMapEditorData {
  context: CaseMapContext;
  data: CaseMapModel;
  helpUrl: string;
  readonly: boolean;
}
export interface CaseMapModel {
  description: string;
  id: string;
  name: string;
  stages: StageModel[];
  uuid: string;
}
export interface StageModel {
  description: string;
  icon: string;
  id: string;
  isTerminating: boolean;
  name: string;
  processes: StageProcessModel[];
  sidesteps: StageProcessModel[];
}
export interface StageProcessModel {
  description: string;
  id: string;
  name: string;
  preCondition: ProcessPreCondition;
  processToExecute: string;
}
export interface ProcessPreCondition {
  label: string;
  script: string;
}
export interface CaseMapEditorProcessContext {
  projectFilter: string;
}
export interface CaseMapEditorSaveArgs {
  context: CaseMapContext;
  data: CaseMapModel;
}
export interface EditorFileContent {
  content: string;
}
export interface ProcessStart {
  description: string;
  name: string;
  processName: string;
  processReference: string;
  projectName: string;
  signature: string;
  startDescription: string;
  startName: string;
  userFriendlyRequestPath: string;
}
