/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CaseMapEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}

export interface CaseMapData {
  context: CaseMapEditorDataContext;
  data: CaseMap;
  helpUrl: string;
}

export interface CaseMap {
  uuid: string;
  id: string;
  name: string;
  description?: string;
  stages: Stage[];
}

export interface Stage {
  _key: string;
  id: string;
  name?: string;
  icon?: string;
  isTerminating?: boolean;
  description?: string;
  processes?: StageProcess[];
  sidesteps?: StageProcess[];
}

export interface StageProcess {
  _key: string;
  id: string;
  name?: string;
  description?: string;
  preCondition?: ProcessPreCondition;
  processToExecute?: string;
}

export interface ProcessPreCondition {
  script: string;
  label: string;
}

export interface Void {}
